export const ENABLE_BARCODE_SCANNER = "ENABLE_BARCODE_SCANNER";
export const ENABLE_BIOMETRIC_SCANNER = "ENABLE_BIOMETRIC_SCANNER";
export const DISABLE_BARCODE_SCANNER = "DISABLE_BARCODE_SCANNER";
export const DISABLE_BIOMETRIC_SCANNER = "DISABLE_BIOMETRIC_SCANNER";
